### ISSUE TITLE
The name SK is not defined. 

### ISSUE THREAD

**Issue by GL4D1AT0R** [ostwilkens/aoc2022#1]
Also what is the run command?

**Comment by GL4D1AT0R** [comment]
"'NoneType' object has no attribute 'text'"

**Comment by VedanthR5** [comment]
Im having the same issue.

**Comment by GL4D1AT0R** [comment]
Wait so how did you run the code? 
python main.py 
or 
python main.py day #

also what did you change in the code apart from the open_AI key
Thanks

**Comment by GL4D1AT0R** [comment]
![image](https://user-images.githubusercontent.com/84785529/205780570-dbc5ed74-a69b-415b-b3d8-b2687056bb04.png)
Adding on to this. This does not end also what did you change in the code apart from using an opn_ai api key?

**Comment by VedanthR5** [comment]
I am having the same issue as you so I don't know the fix :)

**Comment by VedanthR5** [comment]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/72107210/205789718-62221d5c-fe63-4c94-9624-e42a771d323b.png">

here is what i get when running the debug

**Comment by stxo7YYA** [comment]
the function call for running the code is at the bottom: solve(2022, 1, 1)
also your requests are likely being blocked: https://www.reddit.com/r/adventofcode/comments/z9dhtd/please_include_your_contact_info_in_the_useragent/

consider solving the problems yourself, no one wants your AI solve on the leaderboard
if you want to solve the problems with AI, please wait for the leaderboard to fill

**Comment by ostwilkens** [comment]
Thank you for your interest, but I am not providing support for this repo. The main point of sharing this code is so people can understand how it was done.
